---
- name: Installer et configurer Apache
  hosts: ec2
  become: yes
  tasks:
    - name: Installer le paquet httpd (Apache)
      yum:
        name: httpd
        state: present

    - name: Démarrer et activer le service httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copier le fichier index.html vers le répertoire de documents root d'Apache
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        mode: '0644'
