- name: nom playbook
  hosts: ec2
  become: true
  tasks:
    - name: Example from an Ansible Playbook
      ansible.builtin.ping:

    - name: Induce an exception to see what happens
      ansible.builtin.ping:
        data: crash